name: CI/CD for master branch

on:
  # Runs this workflow for the default-branch only
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Initiated by
      run: |
        echo "Initiated by: ${GITHUB_ACTOR}"
    - name: Fetch tags
      run: |
        git fetch --prune --unshallow --tags
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.4.5' # Define the elixir version [required]
        otp-version: '20.1' # Define the OTP version [required]
        experimental-otp: true
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Setup
      env:
        MIX_ENV: test
      run: mix setup
    - name: Run tests
      run: mix test
